'use strict';
/* ---------- built-in feature library & restriction enzymes ---------- */

/* seq = DNA (matched on both strands, mismatches tolerated for long features); aa = protein motif (matched in all 6 frames) */
const BUILTIN_FEATURES = [
  { name: 'CMV enhancer', type: 'enhancer', seq: 'GACATTGATTATTGACTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGCCCAACGACCCCCGCCCATTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCCATTGACGTCAATGGGTGGAGTATTTACGGTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCCCCTATTGACGTCAATGACGGTAAATGGCCCGCCTGGCATTATGCCCAGTACATGACCTTATGGGACTTTCCTACTTGGCAGTACATCTACGTATTAGTCATCGCTATTACCATG' },
  { name: 'CMV promoter', type: 'promoter', seq: 'GTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTGACTCACGGGGATTTCCAAGTCTCCACCCCATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCAAAATGTCGTAACAACTCCGCCCCATTGACGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCT' },
  { name: 'SV40 promoter', type: 'promoter', seq: 'CTGTGGAATGTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAGCAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCGGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAA' },
  { name: 'SV40 ori', type: 'rep_origin', seq: 'ATCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGACTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCGGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGGAGGCCTAGGCTTTTGCAAA' },
  { name: 'T7 promoter', type: 'promoter', seq: 'TAATACGACTCACTATAGGG' },
  { name: 'T3 promoter', type: 'promoter', seq: 'AATTAACCCTCACTAAAGGG' },
  { name: 'SP6 promoter', type: 'promoter', seq: 'ATTTAGGTGACACTATAG' },
  { name: 'lac promoter', type: 'promoter', seq: 'TTTACACTTTATGCTTCCGGCTCGTATGTTG' },
  { name: 'lac operator', type: 'protein_bind', seq: 'TTGTGAGCGGATAACAA' },
  { name: 'CAP binding site', type: 'protein_bind', seq: 'ATGTGAGTTAGCTCACTCAT' },
  { name: 'AmpR promoter', type: 'promoter', seq: 'CGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATTGAAAAAGGAAGAGT' },
  { name: 'AmpR', type: 'CDS', color: '#e5484d', seq: 'ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA' },
  { name: 'KanR', type: 'CDS', color: '#e5484d', seq: 'ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGA' },
  { name: 'PuroR', type: 'CDS', color: '#e5484d', seq: 'ATGACCGAGTACAAGCCCACGGTGCGCCTCGCCACCCGCGACGACGTCCCCAGGGCCGTACGCACCCTCGCCGCCGCGTTCGCCGACTACCCCGCCACGCGCCACACCGTCGATCCGGACCGCCACATCGAGCGGGTCACCGAGCTGCAAGAACTCTTCCTCACGCGCGTCGGGCTCGACATCGGCAAGGTGTGGGTCGCGGACGACGGCGCCGCGGTGGCGGTCTGGACCACGCCGGAGAGCGTCGAAGCGGGGGCGGTGTTCGCCGAGATCGGCCCGCGCATGGCCGAGTTGAGCGGTTCCCGGCTGGCCGCGCAGCAACAGATGGAAGGCCTCCTGGCGCCGCACCGGCCCAAGGAGCCCGCGTGGTTCCTGGCCACCGTCGGCGTCTCGCCCGACCACCAGGGCAAGGGTCTGGGCAGCGCCGTCGTGCTCCCCGGAGTGGAGGCGGCCGAGCGCGCCGGGGTGCCCGCCTTCCTGGAGACCTCCGCGCCCCGCAACCTCCCCTTCTACGAGCGGCTCGGCTTCACCGTCACCGCCGACGTCGAGGTGCCCGAAGGACCGCGCACCTGGTGCATGACCCGCAAGCCCGGTGCCTGA' },
  { name: 'ori', type: 'rep_origin', seq: 'TTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAA' },
  { name: 'f1 ori', type: 'rep_origin', seq: 'ACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTTTAACAAAATATTAACGCTTACAATTT' },
  { name: 'bGH poly(A) signal', type: 'polyA_signal', seq: 'CTGTGCCTTCTAGTTGCCAGCCATCTGTTGTTTGCCCCTCCCCCGTGCCTTCCTTGACCCTGGAAGGTGCCACTCCCACTGTCCTTTCCTAATAAAATGAGGAAATTGCATCGCATTGTCTGAGTAGGTGTCATTCTATTCTGGGGGGTGGGGTGGGGCAGGACAGCAAGGGGGAGGATTGGGAAGACAATAGCAGGCATGCTGGGGATGCGGTGGGCTCTATGG' },
  { name: 'SV40 poly(A) signal', type: 'polyA_signal', seq: 'AACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTA' },
  { name: 'T7 terminator', type: 'terminator', seq: 'CTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTG' },
  { name: 'EGFP', type: 'CDS', color: '#7bc96f', seq: 'ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA' },
  { name: 'mCherry', type: 'CDS', color: '#e0575f', seq: 'ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCTCCGAGCGGATGTACCCCGAGGACGGCGCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAA' },
  { name: 'attB1', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'ACAAGTTTGTACAAAAAAGCAGGCT' },
  { name: 'attB2', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'ACCCAGCTTTCTTGTACAAAGTGGT' },
  // Gateway att sites (arms verified against published Gateway vector sequences in GenBank: MH048881, MG188316, PQ197128, LC217877; attP = attL/attR arms joined at the core)
  { name: 'attP1', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'CAAATAATGATTTTATTTTGACTGATAGTGACCTGTTCGTTGCAACAAATTGATGAGCAATGCTTTTTTATAATGCCAACTTTGTACAAAAAAGCTGAACGAGAAACGTAAAATGATATAAATATCAATATATTAAATTAGATTTTGCATAAAAAACAGACTACATAATACTGTAAAACACAACATATCCAGTCACTATG' },
  { name: 'attP2', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'CATAGTGACTGGATATGTTGTGTTTTACAGTATTATGTAGTCTGTTTTTTATGCAAAATCTAATTTAATATATTGATATTTATATCATTTTACGTTTCTCGTTCAGCTTTCTTGTACAAAGTTGGCATTATAAGAAAGCATTGCTTATCAATTTGTTGCAACGAACAGGTCACTATCAGTCAAAATAAAATCATTATTTG' },
  { name: 'attL1', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'CAAATAATGATTTTATTTTGACTGATAGTGACCTGTTCGTTGCAACAAATTGATGAGCAATGCTTTTTTATAATGCCAACTTTGTACAAAAAAGCAGGCT' },
  { name: 'attL2', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'ACCCAGCTTTCTTGTACAAAGTTGGCATTATAAGAAAGCATTGCTTATCAATTTGTTGCAACGAACAGGTCACTATCAGTCAAAATAAAATCATTATTTG' },
  { name: 'attR1', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'ACAAGTTTGTACAAAAAAGCTGAACGAGAAACGTAAAATGATATAAATATCAATATATTAAATTAGATTTTGCATAAAAAACAGACTACATAATACTGTAAAACACAACATATCCAGTCACTATG' },
  { name: 'attR2', type: 'misc_recomb', color: '#e08fb5', group: 'att', seq: 'CATAGTGACTGGATATGTTGTGTTTTACAGTATTATGTAGTCTGTTTTTTATGCAAAATCTAATTTAATATATTGATATTTATATCATTTTACGTTTCTCGTTCAGCTTTCTTGTACAAAGTGGT' },
  { name: 'M13 fwd', type: 'primer_bind', seq: 'GTAAAACGACGGCCAG' },
  { name: 'M13 rev', type: 'primer_bind', seq: 'CAGGAAACAGCTATGAC' },
  { name: 'pUC MCS', type: 'misc_feature', color: '#8f96a3', seq: 'GAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTT' },
  // protein-level motifs (found in any frame / strand)
  { name: '6xHis', type: 'misc_feature', color: '#b45fd1', aa: 'HHHHHH' },
  { name: 'FLAG', type: 'misc_feature', color: '#b45fd1', aa: 'DYKDDDDK' },
  { name: 'HA', type: 'misc_feature', color: '#b45fd1', aa: 'YPYDVPDYA' },
  { name: 'Myc', type: 'misc_feature', color: '#b45fd1', aa: 'EQKLISEEDL' },
  { name: 'V5', type: 'misc_feature', color: '#b45fd1', aa: 'GKPIPNPLLGLDST' },
  { name: 'Strep-tag II', type: 'misc_feature', color: '#b45fd1', aa: 'WSHPQFEK' },
  { name: 'T7 tag', type: 'misc_feature', color: '#b45fd1', aa: 'MASMTGGQQMG' },
  { name: 'SV40 NLS', type: 'misc_feature', color: '#d98ad0', aa: 'PKKKRKV' },
  { name: 'TEV site', type: 'misc_feature', color: '#d98ad0', aa: 'ENLYFQG' },
  { name: 'HRV 3C site', type: 'misc_feature', color: '#d98ad0', aa: 'LEVLFQGP' },
  { name: 'Thrombin site', type: 'misc_feature', color: '#d98ad0', aa: 'LVPRGS' },
  { name: 'P2A', type: 'misc_feature', color: '#d98ad0', aa: 'ATNFSLLKQAGDVEENPGP' },
];

function userLibrary() { return store.get('userLib', []); }
function saveUserLibrary(l) { store.set('userLib', l); if (typeof requestUpdate === 'function') requestUpdate(true); }   // refresh the library badges in the Features panel
function fullLibrary() {
  const user = userLibrary(); const names = new Set(user.map(u => u.name.toLowerCase()));
  return user.map(u => ({ ...u, user: true })).concat(BUILTIN_FEATURES.filter(b => !names.has(b.name.toLowerCase())));
}

/* Restriction enzymes: '^' = top-strand cut, '_' = bottom-strand cut (omit '_' for palindromic sites). */
const ENZYME_DEFS = `AatII GACGT^C
AccI GT^MKAC
AclI AA^CGTT
AfeI AGC^GCT
AflII C^TTAAG
AflIII A^CRYGT
AgeI A^CCGGT
AhdI GACNNN^NNGTC
AluI AG^CT
AlwI GGATCNNNN^N_
AlwNI CAGNNN^CTG
ApaI GGGCC^C
ApaLI G^TGCAC
ApoI R^AATTY
AscI GG^CGCGCC
AseI AT^TAAT
AsiSI GCGAT^CGC
AvaI C^YCGRG
AvaII G^GWCC
AvrII C^CTAGG
BamHI G^GATCC
BanI G^GYRCC
BanII GRGCY^C
BbsI GAAGACNN^NNNN_
BbvCI CC^TCAGC
BccI CCATCNNNN^N_
BclI T^GATCA
BglI GCCNNNN^NGGC
BglII A^GATCT
BlpI GC^TNAGC
BmtI GCTAG^C
BpmI CTGGAGNNNNNNNNNNNNNN_NN^
BsaAI YAC^GTR
BsaBI GATNN^NNATC
BsaHI GR^CGYC
BsaI GGTCTCN^NNNN_
BsaJI C^CNNGG
BsaWI W^CCGGW
BsiEI CGRY^CG
BsiHKAI GWGCW^C
BsiWI C^GTACG
BslI CCNNNNN^NNGG
BsmAI GTCTCN^NNNN_
BsmBI CGTCTCN^NNNN_
BsmFI GGGACNNNNNNNNNN^NNNN_
BsmI GAATG_CN^
BspEI T^CCGGA
BspHI T^CATGA
BspMI ACCTGCNNNN^NNNN_
BsrBI CCG^CTC
BsrDI GCAATG_NN^
BsrFI R^CCGGY
BsrGI T^GTACA
BsrI ACTG_GN^
BssHII G^CGCGC
BssSI C^ACGAG
BstAPI GCANNNN^NTGC
BstBI TT^CGAA
BstEII G^GTNACC
BstNI CC^WGG
BstUI CG^CG
BstXI CCANNNNN^NTGG
BstYI R^GATCY
BstZ17I GTA^TAC
Bsu36I CC^TNAGG
BtgI C^CRYGG
BtsI GCAGTG_NN^
Cac8I GCN^NGC
ClaI AT^CGAT
DdeI C^TNAG
DpnII ^GATC
DraI TTT^AAA
DraIII CACNNN^GTG
EaeI Y^GGCCR
EagI C^GGCCG
EarI CTCTTCN^NNN_
Esp3I CGTCTCN^NNNN_
BpiI GAAGACNN^NNNN_
BspQI GCTCTTCN^NNN_
PaqCI CACCTGCNNNN^NNNN_
BtgZI GCGATGNNNNNNNNNN^NNNN_
Eco53kI GAG^CTC
EcoNI CCTNN^NNNAGG
EcoO109I RG^GNCCY
EcoRI G^AATTC
EcoRV GAT^ATC
FokI GGATGNNNNNNNNN^NNNN_
FseI GGCCGG^CC
FspI TGC^GCA
Fnu4HI GC^NGC
HaeII RGCGC^Y
HaeIII GG^CC
HhaI GCG^C
HincII GTY^RAC
HindIII A^AGCTT
HinfI G^ANTC
HinP1I G^CGC
HpaI GTT^AAC
HpaII C^CGG
HphI GGTGANNNNNNN_N^
Hpy188I TCN^GA
Hpy99I CGWCG^
HpyCH4III ACN^GT
HpyCH4IV A^CGT
HpyCH4V TG^CA
KasI G^GCGCC
KpnI GGTAC^C
MaeIII ^GTNAC
MboI ^GATC
MboII GAAGANNNNNNN_N^
MfeI C^AATTG
MluI A^CGCGT
MlyI GAGTCNNNNN^_
MmeI TCCRACNNNNNNNNNNNNNNNNNN_NN^
MnlI CCTCNNNNNN_N^
MscI TGG^CCA
MseI T^TAA
MslI CAYNN^NNRTG
MspA1I CMG^CKG
MspI C^CGG
MwoI GCNNNNN^NNGC
NaeI GCC^GGC
NarI GG^CGCC
NciI CC^SGG
NcoI C^CATGG
NdeI CA^TATG
NgoMIV G^CCGGC
NheI G^CTAGC
NlaIII CATG^
NlaIV GGN^NCC
NotI GC^GGCCGC
NruI TCG^CGA
NsiI ATGCA^T
NspI RCATG^Y
PacI TTAAT^TAA
PaeR7I C^TCGAG
PciI A^CATGT
PflFI GACN^NNGTC
PflMI CCANNNN^NTGG
PleI GAGTCNNNN^N_
PmeI GTTT^AAAC
PmlI CAC^GTG
PshAI GACNN^NNGTC
PsiI TTA^TAA
PspGI ^CCWGG
PspOMI G^GGCCC
PspXI VC^TCGAGB
PstI CTGCA^G
PvuI CGAT^CG
PvuII CAG^CTG
RsaI GT^AC
SacI GAGCT^C
SacII CCGC^GG
SalI G^TCGAC
Sau3AI ^GATC
Sau96I G^GNCC
SbfI CCTGCA^GG
ScaI AGT^ACT
ScrFI CC^NGG
SexAI A^CCWGGT
SfaNI GCATCNNNNN^NNNN_
SfcI C^TRYAG
SfiI GGCCNNNN^NGGCC
SgfI GCGAT^CGC
SgrAI CR^CCGGYG
SmaI CCC^GGG
SmlI C^TYRAG
SnaBI TAC^GTA
SpeI A^CTAGT
SphI GCATG^C
SrfI GCCC^GGGC
SspI AAT^ATT
StuI AGG^CCT
StyI C^CWWGG
SwaI ATTT^AAAT
TaqI T^CGA
TfiI G^AWTC
TseI G^CWGC
Tsp509I ^AATT
XbaI T^CTAGA
XcmI CCANNNNN^NNNNTGG
XhoI C^TCGAG
XmaI C^CCGGG
XmnI GAANN^NNTTC
ZraI GAC^GTC`;

function compileEnzyme(name, def) {
  let top = null, bot = null, site = '';
  for (const c of def) {
    if (c === '^') top = site.length;
    else if (c === '_') bot = site.length;
    else site += c;
  }
  if (!/^[ACGTRYKMSWBDHVN]+$/.test(site)) return null;
  if (top === null) top = site.length; // e.g. "CCTC" w/o cut info → treat as cutting after site
  if (bot === null) bot = site.length - top;
  const rc = revcomp(site);
  const lead = site.match(/^N*/)[0].length, trail = site.match(/N*$/)[0].length;
  return { name, lead, trail, rcLead: rc.match(/^N*/)[0].length, rcTrail: rc.match(/N*$/)[0].length, def, site, top, bot, len: site.length, palin: rc === site, rcRegex: new RegExp('(?=(' + iupacRegexSrc(rc) + '))', 'g'), regex: new RegExp('(?=(' + iupacRegexSrc(site) + '))', 'g') };
}

/* Type IIS enzymes commonly used for Golden Gate / MoClo / GoldenBraid assembly */
const GOLDEN_GATE = new Set(['BsaI', 'BsmBI', 'Esp3I', 'BbsI', 'BpiI', 'SapI', 'BspQI', 'AarI', 'PaqCI', 'BtgZI', 'EarI', 'BsmAI', 'BspMI']);
let ENZYMES = [];
let enzVersion = 0;
function buildEnzymes() {
  const list = [];
  for (const line of ENZYME_DEFS.split('\n')) {
    const [n, d] = line.trim().split(/\s+/); if (!n || !d || d === 'skip') continue;
    const e = compileEnzyme(n, d); if (e) list.push(e);
  }
  const have = new Set(list.map(e => e.name));
  if (typeof nebExtraDefs === 'function') for (const [n, d] of nebExtraDefs()) { if (have.has(n)) continue; const e = compileEnzyme(n, d); if (e) { e.neb = true; list.push(e); have.add(n); } }
  for (const u of store.get('userEnzymes', [])) { if (have.has(u.name)) continue; const e = compileEnzyme(u.name, u.def); if (e) { e.user = true; list.push(e); } }
  list.sort((a, b) => a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }));
  ENZYMES = list; enzVersion++;
}
